namespace: nginx-ingress
helmCharts:
  - name: nginx-ingress
    repo: https://helm.nginx.com/stable
    version: 0.18.1
    releaseName: nginx-ingress
    namespace: nginx-ingress
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - nginx-regcred.yaml
  - tls.yaml
patchesStrategicMerge:
  - configmap.yaml
