controller:
  hostNetwork: true
  strategy:
    type: Recreate
  serviceAccount:
    imagePullSecretName: regcred
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
  nginxplus: true
  enableSnippets: true
  enableLatencyMetrics: true
  appprotect:
    enable: true
  appprotectdos:
    enable: true
    maxDaemons: 4
    # maxWorkers: 8
    # memory: 80
    debug: false
  config:
    name: nginx-config
  setAsDefaultIngress: true
  service:
    type: NodePort
    httpPort:
      nodePort: 30080
    httpsPort:
      nodePort: 30443
  defaultTLS:
    secret: nginx-ingress/f5labs.dev
  wildcardTLS:
    secret: nginx-ingress/f5labs.dev
