apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: "hapi-waf-default-swagger-enforcement-bot-blocking-policy"
spec:
  policy:
    name: "hapi-waf-default-swagger-enforcement-bot-blocking-policy"
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    open-api-files:
      - link: "https://raw.githubusercontent.com/apcj-f5/nap-devsecops-demo/master/tests/hapi/hapi-swagger.json"
    bot-defense:
      settings:
        isEnabled: true
      mitigations:
        classes:
          - name: malicious-bot
            action: block
