apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hapi
    app.kubernetes.io/instance: hapi
  name: hapi
  namespace: hapi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hapi
  type: ClusterIP
status:
  loadBalancer: {}
