apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: "hapi-waf-log-policy"
spec:
  content:
    format: default
    max_message_size: 64k
    max_request_size: any
  filter:
    request_type: illegal
