apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: hapi-ingress-policy
spec:
  waf:
    enable: true
    apPolicy: hapi-waf-default-transparent-policy
    securityLogs:
      - enable: true
        apLogConf: hapi-waf-log-policy
        logDest: stderr
