apiVersion: appprotectdos.f5.com/v1beta1
kind: APDosLogConf
metadata:
  name: "hapi-dos-log-policy"
spec:
  filter:
    traffic-mitigation-stats: all
    bad-actors: top 10
    attack-signatures: top 10
