apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
  name: dos-protected
spec:
  enable: true
  name: "hapi.f5labs.dev"
  apDosMonitor:
    uri: "hapi.f5labs.dev"
  apDosPolicy: "dos-policy"
  dosSecurityLog:
    enable: true
    apDosLogConf: "doslogconf"
    dosLogDest: stderr
