apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "nap-waf-ingress-policy"
    securityLogs:
      - enable: true
        apLogConf: logconf
        logDest: stderr
