apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: alarm-bots
    securityLogs:
    - enable: true
      apLogConf: logconf
      logDest: stderr
