namespace: grafana
helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: prometheus
    includeCRDs: true
    valuesFile: values.yaml
