services:
  - docker:dind

build-container:
  stage: build
  image:
    name: tmaier/docker-compose:latest
  only:
    changes:
      - Dockerfile
      - docker-compose.yml
      - pom.xml
      - src/*
  script:
    - docker-compose up -d --build
  allow_failure: false
