services:
  - docker:dind

variables:
  APP_NAME: hapi-fhir_jpaserver

push-to-registry:
  stage: package
  image:
    name: docker:latest
  only:
    changes:
      - Dockerfile
      - docker-compose.yml
      - pom.xml
      - src/*
  script:
    - docker build -t $APP_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
    - docker images
    - docker login --username $APP_REGISTRY_ID --password $APP_REGISTRY_PWD $APP_REGISTRY
    - docker push $APP_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
  allow_failure: false
