apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: "bank-ingress-policy"
spec:
  waf:
    enable: true
    apPolicy: "bank-waf-policy"
    securityLogs:
      - enable: true
        apLogConf: "bank-waf-log-policy"
        logDest: stderr
