apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: "nap-waf-ingress-policy"
spec:
  policy:
    name: sigs-enabled-bots-disabled-dos-enabled
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    blocking-settings:
      violations:
        - name: VIOL_RATING_THREAT
          alarm: false
          block: true
        - name: VIOL_RATING_NEED_EXAMINATION
          alarm: true
          block: false
        - name: VIOL_THREAT_CAMPAIGN
          alarm: false
          block: true
    signature-sets:
      - name: High Accuracy Signatures
        alarm: false
        block: true
      - name: High Accuracy Detection Evasion Signatures
        alarm: false
        block: true
      - name: Server Side Code Injection Signatures
        alarm: false
        block: true
      - name: Generic Detection Signatures (High Accuracy)
        alarm: false
        block: true
    bot-defense:
      settings:
        isEnabled: true
      mitigations:
        classes:
          - name: trusted-bot
            action: ignore
          - name: untrusted-bot
            action: ignore
          - name: malicious-bot
            action: ignore
          - name: browser
            action: ignore
          - name: suspicious-browser
            action: ignore
          - name: unknown
            action: ignore
