apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
  name: "bank-dos-protected-resource"
spec:
  enable: true
  name: "bank.f5labs.dev"
  # apDosMonitor:
  # uri: "bank.f5labs.dev"
  # protocol: "http1"
  # timeout: 5
  apDosPolicy: "bank-dos-policy"
  dosAccessLogDest: stderr
  dosSecurityLog:
    enable: true
    apDosLogConf: "bank-dos-log-policy"
    dosLogDest: stderr
