apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nginx-dashboards
  namespace: nginx-ingress
spec:
  host: apps.f5labs.dev
  tls:
    redirect:
      enable: true
  upstreams:
    - name: nginx-dashboards
      service: nginx-dashboards
      port: 8080
  routes:
    - path: /
      action:
        pass: nginx-dashboards
