apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: argocd
  namespace: argocd
spec:
  host: build.f5labs.dev
  tls:
    redirect:
      enable: true
  upstreams:
    - name: argocd-server
      service: argocd-server
      port: 443
  routes:
    - path: /
      action:
        pass: argocd-server
