apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/apcj-f5/nap-devsecops-demo.git
    targetRevision: deploy
    path: argocd/manifests/bank/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions: [CreateNamespace=true]
