apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/apcj-f5/nap-devsecops-demo.git
    targetRevision: deploy
    path: argocd/manifests/gql/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
