apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securecodebox
  namespace: securecodebox
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/apcj-f5/nap-devsecops-demo.git
      targetRevision: deploy
      path: argocd/manifests/securecodebox
  destination:
    namespace: securecodebox
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - ServerSideApply=true
