apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: emqx1
  name: emqx1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emqx1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mqtt-lb-nginx-plus-default: "true"
        io.kompose.service: emqx1
    spec:
      containers:
        - env:
            - name: EMQX_CLUSTER__DISCOVERY_STRATEGY
              value: static
            - name: EMQX_CLUSTER__STATIC__SEEDS
              value: emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io,emqx3@emqx3-cluster.emqx.io
            - name: EMQX_NODE__NAME
              value: emqx1@emqx1-cluster.emqx.io
          image: emqx/emqx:5.3.0
          name: emqx1
          ports:
            - containerPort: 18083
              hostPort: 18083
              protocol: TCP
          resources: {}
      hostname: emqx1-cluster.emqx.io
      restartPolicy: Always
status: {}
