apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: mqtt
  namespace: mqtt
spec:
  host: mqtt.f5labs.dev
  tls:
    redirect:
      enable: true
  upstreams:
    - name: emqx-core
      service: emqx-listeners
      port: 18083
  routes:
    - path: /
      action:
        pass: emqx-core
