namespace: nginx-ingress
helmCharts:
  - name: nginx-appprotect-dos-arbitrator
    repo: https://helm.nginx.com/stable
    version: 0.1.0
    releaseName: nginx-appprotect-dos-arbitrator
    namespace: nginx-ingress
    includeCRDs: true
    valuesFile: values.yaml
