namespace: kube-system
helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml
# resources: [transport-server-mqtt.yaml, virtual-server-mqtt.yaml]
