services:
  - docker:dind

sec-source_scan:
  stage: sec-pre_build
  image:
    name: shiftleft/scan
  before_script:
    - set -x SCAN_DEBUG_MODE=debug
  script:
    - scan --src /src --type credscan,java,yaml --out_dir /app/reports
  artifacts:
    paths: [/app/reports/.sastscan.baseline]
    when: always
    expire_in: one week
  allow_failure: true
