apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-completed-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      labels:
        name: sync-completed
    spec:
      containers:
        # executes newman test and record result in shared dir /tmp/newman/return_code
        - name: newman
          command: [/scripts/newman_run.sh]
          image: postman/newman
          volumeMounts:
            - name: postsync-scripts
              mountPath: /scripts/newman_run.sh
              subPath: newman_run.sh
            - name: shared-data
              mountPath: /tmp/newman/
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false # image runs as root :(
        # waits for newman test results in /tmp/newman/return_code and updates commit status
        - name: notify-newman-results
          command: [/scripts/check_newman_run.sh]
          image: badouralix/curl-jq
          volumeMounts:
            - name: postsync-scripts
              mountPath: /scripts/check_newman_run.sh
              subPath: check_newman_run.sh
            - name: postsync-scripts
              mountPath: /scripts/set_commit_status.sh
              subPath: set_commit_status.sh
            - name: shared-data
              mountPath: /tmp/newman/
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github
                  key: pat
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false # image runs as root :(
      volumes:
        - name: postsync-scripts
          configMap:
            name: postsync-scripts
            defaultMode: 0755
        - name: shared-data
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
