apiVersion: v1
kind: ConfigMap
metadata:
  name: postsync-scripts
data:
  trigger_post_deployment_workflow.sh: |
    #!/usr/bin/env sh
    set -e

    echo "Get post deployment workflow ID (Newman tests)"

    WORKFLOW_ID=$(curl --fail -s -L \
      https://api.github.com/repos/apcj-f5/nap-devsecops-demo/actions/workflows \
      | jq -r '.workflows[] | select(.name=="Newman tests") | .id')

    echo "Trigger post deployment Github workflow (ID=$WORKFLOW_ID)"

    curl --fail -s -L -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -d '{"ref": "deploy"}' \
      https://api.github.com/repos/apcj-f5/nap-devsecops-demo/actions/workflows/$WORKFLOW_ID/dispatches
  set_commit_status.sh: |
    #!/usr/bin/env sh
    set -e

    COMMIT_STATE=$1
    COMMIT_STATUS_DESCRIPTION=$2

    generate_post_data()
    {
      cat <<EOF
    {
      "state": "$COMMIT_STATE",
      "target_url": "https://github.com/apcj-f5/nap-devsecops-demo/actions",
      "description": "$COMMIT_STATUS_DESCRIPTION",
      "context": "ArgoCD"
    }
    EOF
    }

    echo "Get commit SHA by 'deploy' tag"
    COMMIT_SHA=$(curl --fail -s -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/apcj-f5/nap-devsecops-demo/commits/deploy \
      | jq -r .sha)

    echo "Set commit status for commit $COMMIT_SHA to $COMMIT_STATE"
    curl --fail -s -L -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GITHUB_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -d "$(generate_post_data)" \
      https://api.github.com/repos/apcj-f5/nap-devsecops-demo/statuses/$COMMIT_SHA
