apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gql
    app.kubernetes.io/instance: gql
  name: gql
  namespace: gql
spec:
  ports:
    - port: 5013
      protocol: TCP
      targetPort: 5013
  selector:
    app: gql
  type: ClusterIP
status:
  loadBalancer: {}
