apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: gql
spec:
  host: gql.f5labs.dev
  # policies:
  # - name: waf-policy
  # dos: dos-protected
  tls:
    redirect:
      enable: true
  upstreams:
    - name: gql
      service: gql
      port: 5013
  routes:
    - path: /
      action:
        pass: gql
