apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gql
  name: gql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gql
    spec:
      containers:
        - image: shsingh/dvgql
          name: gql
          securityContext:
# allowPrivilegeEscalation: false
# runAsNonRoot: true
