name: "bank.f5labs.dev - Functional Testing"
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-k6-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 bank.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@6bf1c0facb2730aac9f4929e41dfddd8f4b8621b # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run k6 baseline test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/bank/bank-k6-tests-baseline.js
          flags: --vus 50 --duration 10s
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@6bf1c0facb2730aac9f4929e41dfddd8f4b8621b # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
