name: "bank.f5labs.dev - Functional Testing"
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-k6-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 bank.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@1f65b503baf942683e5b79059a18530d783318e6 # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Run k6 baseline test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/bank/bank-k6-tests-baseline.js
          flags: --vus 50 --duration 10s
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@1f65b503baf942683e5b79059a18530d783318e6 # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
