name: "Github - Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: github/issue-labeler@v3.4 #May not be the latest version
        with:
          configuration-path: .github/issue-labeler-config.yml
          enable-versioned-regex: 0
          include-title: 1
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
