---
name: Github - Tag commit for deployment
on:
  push:
    branches: [master]
    paths-ignore: [.github/**, "*.md"]
permissions:
  contents: read
jobs:
  pre_deployment_checks:
    if: github.repository_owner == 'apcj-f5'
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Run Script
        run: |
          export GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          ${GITHUB_WORKSPACE}/.github/scripts/check-precommit.sh
      - name: Tag Commit
        run: |
          git tag --force deploy
          git push --force origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
