name: "Github - Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: github/issue-labeler@v3.2 #May not be the latest version
        with:
          configuration-path: .github/issue-labeler-config.yml
          enable-versioned-regex: 0
          include-title: 1
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
