name: "gql.f5labs.dev - ZAP Full Scan"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 00 * * 6"
# Declare default permissions as read only.
permissions: read-all
jobs:
  zap-baseline:
    name: "ZAP Full Scan"
    runs-on: ubuntu-latest
    permissions:
      # Needed to write to Issues.
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "https://gql.f5labs.dev"
          issue_title: "gql.f5labs.dev - OWASP ZAP Full Scan"
          fail_action: "true"
          cmd_options: "-I"
