name: "hapi.f5labs.dev - Functional Testing"
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-newman-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 hapi.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@e8094a178c31faea9401e57a283f9b9b1997bc45 # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: matt-ball/newman-action@d4b17b1f5b137507e65c9426171155f95caec012 # master
        with:
          collection: tests/hapi/hapi-newman-tests-collection.json
          environment: tests/hapi/hapi-newman-tests-environment.json
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@e8094a178c31faea9401e57a283f9b9b1997bc45 # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
