name: "hapi.f5labs.dev - ZAP Baseline Scan"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 00 * * *"
# Declare default permissions as read only.
permissions: read-all
jobs:
  zap-baseline:
    name: "ZAP Baseline Scan"
    runs-on: ubuntu-latest
    permissions:
      # Needed to write to Issues.
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          target: "https://hapi.f5labs.dev"
          issue_title: "hapi.f5labs.dev - OWASP ZAP Baseline Scan"
          fail_action: "true"
          cmd_options: "-I"
