name: "hapi.f5labs.dev - Functional Testing"
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-newman-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 hapi.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@814b36ec1b41ab8bf434331d8220c08a9e4cbc40 # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: matt-ball/newman-action@d4b17b1f5b137507e65c9426171155f95caec012 # master
        with:
          collection: tests/hapi/hapi-newman-tests-collection.json
          environment: tests/hapi/hapi-newman-tests-environment.json
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@814b36ec1b41ab8bf434331d8220c08a9e4cbc40 # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
