name: "hapi.f5labs.dev - Functional Testing"
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-newman-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 hapi.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@542eeef9b2131b933a56aa0d14467f933b9350f7 # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: matt-ball/newman-action@170d252f10d199d75d6be4c739b48a3bd5f15ece # master
        with:
          collection: tests/hapi/hapi-newman-tests-collection.json
          environment: tests/hapi/hapi-newman-tests-environment.json
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@542eeef9b2131b933a56aa0d14467f933b9350f7 # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
