name: Newman tests
on: workflow_dispatch
permissions:
  contents: read
jobs:
  run-newman-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: api.github.com:443 github.com:443 hapi.f5labs.dev:443
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@853d2f0b17ca3a0854deffe52d8c92675f923c61 # master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: matt-ball/newman-action@d4b17b1f5b137507e65c9426171155f95caec012 # master
        with:
          collection: tests/hapi/hapi-newman-tests-collection.json
          environment: tests/hapi/hapi-newman-tests-environment.json
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@853d2f0b17ca3a0854deffe52d8c92675f923c61 # master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: ${{ github.workflow }}
