name: Newman tests
on: workflow_dispatch
jobs:
  run-newman-tests:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: GithubActions - ${{ github.workflow }}
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: matt-ball/newman-action@master
        with:
          collection: tests/hapi/hapi-newman-tests-collection.json
          environment: tests/hapi/hapi-newman-tests-environment.json
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: GithubActions - ${{ github.workflow }}
