name: Tag commit for deployment
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      # - "*.md"
permissions:
  contents: read
jobs:
  pre_deployment_checks:
    if: github.repository_owner == 'apcj-f5'
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Run Script
        run: |
          export GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          ${GITHUB_WORKSPACE}/.github/scripts/check-workflow.sh "Semgrep"
          ${GITHUB_WORKSPACE}/.github/scripts/check-workflow.sh "OpenSSF Scorecard"
          ${GITHUB_WORKSPACE}/.github/scripts/check-precommit.sh
      - name: Tag Commit
        run: |
          git tag --force deploy
          git push --force origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
